Fix clang equality comparison warning in generated [eu]bpf (and xdp) code
p4lang/p4c pull request #2568
Opened 2020-09-24 17:59 UTC by levaitamas

I am trying to compile a toy P4 program to XDP. But, clang warns me about an equality comparison in if statement condition.

#### Problematic snippet in P4:

```p4
control Ingress(inout Headers hdr, in xdp_input xin, out xdp_output xout) {
    apply {
        xout.output_port = 0;
        xout.output_action = xdp_action.XDP_DROP;
        if (hdr.udp.isValid()) {
	  if (hdr.udp.dstPort == 16w1234) {
	    hdr.udp.dstPort = 16w1235;
	  }
	  xout.output_action = xdp_action.XDP_PASS;
        }
    }

}
```

#### C code generated via `p4c-xdp basic.p4 -o basic.c`:

```c

    accept:
    {
        u8 hit;
        {
xout.output_port = 0;
            xout.output_action = XDP_DROP;
            if (/* hd.udp.isValid()*/
            hd.udp.ebpf_valid) {
if ((hd.udp.dstPort == 1234))
                    hd.udp.dstPort = 1235;
                xout.output_action = XDP_PASS;
            }
        }
    }
```

And the clang (version 9.0.1-14) warning:

```sh
basic.c:224:21: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
if ((hd.udp.dstPort == 1234))
     ~~~~~~~~~~~~~~~^~~~~~~
basic.c:224:21: note: remove extraneous parentheses around the comparison to silence this warning
if ((hd.udp.dstPort == 1234))
    ~               ^      ~
basic.c:224:21: note: use '=' to turn this equality comparison into an assignment
if ((hd.udp.dstPort == 1234))
                    ^~
                    =
1 warning generated.
```

This PR fixes the warning for me. I am not sure about its generality. It passes `make check-ebpf` and `make check-ubpf`. Comments are welcome.

2020-09-24 18:10 UTC, mbudiu-vmw requested changes
I am not sure this is sound. The parentheses are there to enforce precedence. If this comparison is used within another expression you may get a different result. To do this properly you have to look at the context where the expression is used and the precedence of the parent operator.

2020-09-24 18:12 UTC, levaitamas commented
@mbudiu-vmw I had a similar concern. Thank you for the quick feedback!

2020-09-24 22:03 UTC, hesingh commented
With clang, use `-Wno-parentheses-equality` to disable the warning.

However, it does look silly C code to have duplicate parenthesis.  Makes sense to change p4c code in a manner like what @mbudiu-vmw is saying.  I would add `comparison(const IR::Operation_Relation* b)` to the BFP code and do the analysis there.

2020-09-25 23:00 UTC, hesingh commented
I have sent out a PR to fix this issue.  See

https://github.com/p4lang/p4c/pull/2570/files

2020-09-26 08:44 UTC, levaitamas commented
Awesome, thank you @hesingh!

2020-09-26 08:45 UTC, closed without merging