[PSA] Hash support for PSA model added
p4lang/p4c pull request #2896
Opened 2021-09-03 12:13 UTC by DusanKrdzic

* Added support for checksum in PSA model:
1. Ingress and egress controls recognize PSA Hash instances in their locals and convert them into JSON.
2. Ingress and egress controls recognize PSA Hash methods and convert them into JSON.

* link to behavioral-model pull request: https://github.com/p4lang/behavioral-model/pull/1033

2021-09-03 12:14 UTC, DusanKrdzic commented
Some tests will fail because bm implementation hasn't been merged yet.

2021-09-03 17:40 UTC, mbudiu-vmw commented
> Some tests will fail because the bm implementation hasn't been merged yet.

Even if the implementation is merged, I think we are using an old Docker image for bmv2 which won't be automatically updated anymore.
We may need to make building bmv2 part of our build process, or find some other way to use a prebuilt image.

2021-09-03 17:54 UTC, mbudiu-vmw requested changes

2021-09-03 17:54 UTC, mbudiu-vmw commented on backends/bmv2/common/action.cpp
> +                                                em->method->name.name == "get_hash") {
your indentation is inconsistent.

2021-09-03 17:54 UTC, mbudiu-vmw commented on backends/bmv2/common/action.cpp
> +                        } else
cpplint won't like this else not having braces.

2021-09-03 17:54 UTC, mbudiu-vmw commented on backends/bmv2/common/action.cpp
> +                            BUG("%1%: expected 1 or 3 arguments", mce);
I would suggest using a modelError here instead of a bug (unless you are sure you have validated the arguments before).

2021-09-03 17:54 UTC, mbudiu-vmw commented on backends/bmv2/psa_switch/psaSwitch.cpp
> +        auto fieldList=new Util::JsonObject();
we usually add spaces around =

2021-09-03 17:54 UTC, mbudiu-vmw commented on backends/bmv2/psa_switch/psaSwitch.cpp
> +    UNUSED const IR::ExternBlock* eb, UNUSED const bool& emitExterns) {
eb and c are used, so perhaps you can remove the UNUSED annotation where it is wrong.

2021-09-03 17:54 UTC, mbudiu-vmw commented on backends/bmv2/psa_switch/psaSwitch.cpp
> +        modelError("%1%: expected a member", algo->getNode());
member or declaration?

2021-09-06 10:26 UTC, DusanKrdzic commented
@mbudiu-vmw  I've made changes that have been requested.

2021-09-07 19:46 UTC, mbudiu-vmw commented
@antoninbas do you have any suggestions on how to deal with changes in bmv2?
Could we actually have a release containing binaries?

2021-09-22 16:45 UTC, DusanKrdzic commented
@mbudiu-vmw the bm part of the implemention is merged. Do I need to push an empty commit or?

2021-09-22 16:49 UTC, antoninbas commented
@mbudiu-vmw I stopped relying on auto dockerhub builds to update the bmv2 docker image, since these are no longer available. But I do have a separate CI job (using Github actions) which takes care of updating the image. It's actually faster now than it used to be, and the image has been updated already.

2021-09-22 21:43 UTC, mbudiu-vmw commented
Hopefully an empty commit will pass the tests.
Thank you @antoninbas

2021-09-22 22:25 UTC, DusanKrdzic commented
@mbudiu-vmw I pushed an empty commit, I hope it will pass the tests..

2021-09-23 11:36 UTC, DusanKrdzic commented
@mbudiu-vmw All tests passed.

2021-09-23 18:04 UTC, mbudiu-vmw approved these changes

2021-09-23 18:04 UTC, merged