DPDK: add support for add_on_miss table property
p4lang/p4c pull request #2901
Opened 2021-09-16 01:44 UTC by hanw

This PR implements the support for add_on_miss table property in pna. 

A P4 table with add_on_miss property enabled is translated into the learner table object in DPDK runtime.

The removeComplexExpressions pass is refactored into a midend pass from backend/bmv2 to be used in dpdk backend.

2021-09-16 18:53 UTC, mbudiu-vmw requested changes
You are missing the reference outputs.
You need to document the `add_entry` function. The way it is used in this example makes no sense to me.

2021-09-16 18:53 UTC, mbudiu-vmw commented on backends/dpdk/dpdkProgram.cpp
> +        //
empty comment

2021-09-16 18:53 UTC, mbudiu-vmw commented on backends/dpdk/spec.cpp
> +        out << "\tsize 0x10000" << std::endl;
wouldn't it be nicer to have this be a static variable or something similar?

2021-09-16 18:53 UTC, mbudiu-vmw commented on backends/dpdk/spec.cpp
> +        out << "\ttimeout 120"<< std::endl;
same for default timeout.

2021-09-16 18:53 UTC, mbudiu-vmw commented on testdata/p4_16_samples/pna-add-on-miss.p4
> +        add_entry(action_name="next_hop", action_params = tmp);
tmp is not initialized here. What does this mean?

2021-09-16 19:20 UTC, hanw commented on testdata/p4_16_samples/pna-add-on-miss.p4
> +        add_entry(action_name="next_hop", action_params = tmp);
add_entry is defined in pna.p4 https://github.com/p4lang/pna/blob/main/pna.p4#L668

2021-09-16 20:46 UTC, mbudiu-vmw commented on testdata/p4_16_samples/pna-add-on-miss.p4
> +        add_entry(action_name="next_hop", action_params = tmp);
It may be defined there, but it is not documented at all.

2021-09-16 23:09 UTC, hanw commented
Thanks for the review. I have addressed most of the comments.

2021-09-20 21:05 UTC, mbudiu-vmw commented
This seems to be failing some tests. Please ping me again if you want another review.

2021-09-21 18:17 UTC, hanw commented
@mbudiu-vmw Please take another look?

2021-09-21 23:35 UTC, mbudiu-vmw commented on backends/dpdk/dpdkArch.cpp
> +    auto default_action = t->properties->getProperty("default_action");
So it is ok to have add_on_miss but a default_action which can be changed dynamically by the control plane?

2021-09-21 23:36 UTC, mbudiu-vmw commented on backends/dpdk/spec.h
> +/*
what's this file for?

2021-09-21 23:37 UTC, mbudiu-vmw approved these changes

2021-09-22 16:40 UTC, merged