Fix problems with OutOfBound state creation
p4lang/p4c pull request #2959
Opened 2021-11-22 13:20 UTC by vladyslav-dubina

Example test: all of parserUnroll tests or issue692-bmv2.p4.
Solves problems related to incorrect generation of verify functions and creation of OutOfBound state

2021-11-22 13:37 UTC, fruffy approved these changes

2021-11-22 16:47 UTC, fruffy requested changes

2021-11-22 16:47 UTC, fruffy commented on midend/parserUnroll.h
> +                    new IR::Type_Method(IR::Type::Void::get(), new IR::ParameterList(), "*method"),
The type of the method does not quite match. You add an empty parameter list here, but verify has the type parameters bool and error.

2021-11-23 17:57 UTC, fruffy approved these changes

2021-11-23 19:26 UTC, merged

2021-11-23 19:28 UTC, mbudiu-vmw commented
I didn't have time to review this

2021-11-23 19:30 UTC, fruffy commented
Ah I apologize. This one was fairly small and benign, so I just went ahead and merged it.

2021-11-30 23:53 UTC, mbudiu-vmw commented on testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-test1-midend.p4
> +        transition reject;
this is unreachable, verify(false) will always transition to reject.
https://p4.org/p4-spec/docs/P4-16-v1.2.2.html#sec-verify
So this change is really unnecessary.