DPDK Backend: Convert error codes to its constant values
p4lang/p4c pull request #2966
Opened 2021-11-29 10:21 UTC by usha1830

The error constants defined using `error { }` should be replaced with the constant values for DPDK backend.

- Existing class BranchingInstructionGeneration (with minor additions ) is reused for generating jumps on error code comparison.
- As  error type only supports equality (==) and inequality (!=) comparisons. The operands of these operations are checked.
- Added new testcases and corresponding reference outputs.

2021-11-29 14:26 UTC, mbudiu-vmw reviewed
I think we should have a general midend pass with a policy, like the one which eliminates enum. Why can't you just convert enums to short Integers?

2021-11-29 19:15 UTC, usha1830 commented
> I think we should have a general midend pass with a policy, like the one which eliminates enum. Why can't you just convert enums to short Integers?

I first tried to implement this similar to eliminateSerEnums midend pass. 
```
const IR::Node* DoEliminateErrorCode::preorder(IR::Type_Error* err) {
    return new IR::Type_Bits(32, false);
}

```
However, when I tried to change the type of variables of `error` type to` bit<W>` type, the typechecker failed with the error
_"At this point in the compilation typechecking should not infer new types anymore, but it did."_

I also tried writing a backend pass to achieve this, but the typechecker failed with the same error as above. 
Am I doing something wrong? Is there a way to change the type of existing struct fields and other local variables?

Thanks!

2021-11-29 19:25 UTC, hanw commented
From my experience, typically, the error _"At this point in the compilation typechecking should not infer new types anymore, but it did"_ occurs when you add a variable of Type_InfInt to the program and was later inferred to Type_Bits.

2021-11-29 19:36 UTC, mbudiu-vmw commented
That too, if you replace with constants make sure they have a width

2021-11-29 19:38 UTC, usha1830 commented
> From my experience, typically, the error _"At this point in the compilation typechecking should not infer new types anymore, but it did"_ occurs when you add a variable of Type_InfInt to the program and was later inferred to Type_Bits.

This maybe the issue. 
I replaced the error constant with  _IR::Constant(error_id)_ which is Type_InfInt

2021-11-29 19:55 UTC, usha1830 commented
> That too, if you replace with constants make sure they have a width



> That too, if you replace with constants make sure they have a width

How do we specify width for constants?

2021-11-29 19:56 UTC, mbudiu-vmw commented
Use the right constructor of IR::constant

2021-11-29 20:09 UTC, usha1830 commented
@mbudiu-vmw , @hanw Thanks for the pointers. The typechecker error is gone. Running into some other issues. Will update the PR after fixing the issues.

2021-12-07 12:58 UTC, usha1830 commented
I have updated the PR with a midend pass. The code is similar to convertEnums midend pass, but this new pass should be called towards the end of the Midend passes, so that error types created by other passes (such as HandleNoMatch, ParserUnroll etc) are also converted.

2021-12-07 21:20 UTC, mbudiu-vmw requested changes

2021-12-07 21:20 UTC, mbudiu-vmw commented on backends/dpdk/midend.cpp
> +class ErrorBits : public P4::ChooseErrorRepresentation {
I would call this ErrorOn16Bits or something similar.
Alternatively, the class should be called ErrorWidth and have a constructor argument for the width.

2021-12-07 21:20 UTC, mbudiu-vmw commented on midend/convertErrors.cpp
> +    if (type->toString() == IR::Type_Error::error) {
In general relying on strings is not safe, you should probably use equiv or the typeMap type equivalence checker.

2021-12-07 21:20 UTC, mbudiu-vmw commented on midend/convertErrors.cpp
> +    if (expression->expr->toString() == "error") {
Do not use strings. Rather check the type of the expression to see if it's Error.

2021-12-07 21:20 UTC, mbudiu-vmw commented on midend/convertErrors.cpp
> +/* Copyright 2021 Intel Corporation
There is an alternative way to do this which you may find simpler: convert the Error to a serializable Enum and the rely on the serializable enum conversion pass. This should be simpler than what you have here.

2021-12-08 18:24 UTC, mbudiu-vmw commented
Thinking of this I believe that the policy should also include a function to assign a numeric value to each identifier. Then backends that have hardwired values for the error codes can still use this pass.

2021-12-14 00:47 UTC, mbudiu-vmw approved these changes

2021-12-14 00:47 UTC, merged