Dismantle Mux expression / Ternary operator in dpdk
p4lang/p4c pull request #3087
Opened 2022-02-16 09:55 UTC by kamleshbhalui

LowerExpressions pass which introduces ternary operator (?:) which is not supported in DPDK. 
This PR dismantle ternary operator to if else chain.

2022-02-17 01:34 UTC, mbudiu-vmw requested changes

2022-02-17 01:34 UTC, mbudiu-vmw commented on backends/dpdk/dpdkArch.cpp
> +        left = new IR::PathExpression(IR::ID(varName, pe->path->name.originalName));
why not the srcInfo as well?

2022-02-17 06:53 UTC, kamleshbhalui commented on backends/dpdk/dpdkArch.cpp
> +    typeMap->setType(path, type);
Yes

2022-02-17 06:55 UTC, kamleshbhalui commented on backends/dpdk/backend.cpp
> +        new SimplifyTernaryOperator(typeMap, refMap),
Renamed it to DismantleMuxExpressions.
Looks like Slices taken care by LowerExpressions Pass.

2022-02-17 06:55 UTC, kamleshbhalui commented on backends/dpdk/dpdkArch.cpp
> +    typeMap->setType(path, type);
Yes

2022-02-17 06:55 UTC, kamleshbhalui commented on backends/dpdk/dpdkArch.cpp
> +        left = new IR::PathExpression(IR::ID(varName, pe->path->name.originalName));
done

2022-02-17 17:45 UTC, mbudiu-vmw approved these changes

2022-02-17 17:45 UTC, mbudiu-vmw commented on backends/dpdk/dpdkArch.cpp
> +    (void) addAssignment(expression->srcInfo, tmp, expression->e1);
Are you sure this does not need to be added to the typeMap?
What if you have an expression like a ? (b ? c : d) : (e ? f : g)

2022-02-19 01:45 UTC, kamleshbhalui commented
@mbudiu-vmw Please merge it.

2022-02-19 02:03 UTC, merged