Add support for Checksum extern and CRC16/32 algorithms to eBPF backend
p4lang/p4c pull request #3167
Opened 2022-04-02 07:22 UTC by kmateuszssak

This PR adds Checksum extern and adds support for CRC16 and CRC32 algorithms.

Co-authored-by: Tomasz Osiński <tomasz@opennetworking.org>
Co-authored-by: Jan Palimąka <jan.palimaka@orange.com>

2022-04-04 18:06 UTC, mbudiu-vmw requested changes
This is good, but could use a little more documentation.

2022-04-04 18:06 UTC, mbudiu-vmw commented on backends/ebpf/psa/externs/ebpfPsaHashAlgorithm.cpp
> +    // version may require other method of update. To deal with byte order data
comma after order?

2022-04-04 18:06 UTC, mbudiu-vmw commented on backends/ebpf/psa/externs/ebpfPsaHashAlgorithm.cpp
> +                        "Sub-byte fields have to be aligned to bytes %1%", field);
I don't think I would understand this error message as a user of the compiler.

2022-04-04 18:06 UTC, mbudiu-vmw commented on backends/ebpf/psa/externs/ebpfPsaHashAlgorithm.cpp
> +void CRCChecksumAlgorithm::emitAddData(CodeBuilder* builder,
This code has several layers of indirection for generating a string that becomes C code, so it's not easy to read.
Can you add a comment showing some final generated code?

2022-04-04 18:06 UTC, mbudiu-vmw commented on backends/ebpf/psa/externs/ebpfPsaHashAlgorithm.h
> +class CRC16ChecksumAlgorithm : public CRCChecksumAlgorithm {
Perhaps you can add a comment describing how this protocol is used to compute the checksum: how these values are used, and what is the order that these methods are called in the generated code.

2022-04-06 13:22 UTC, kmateuszssak commented on backends/ebpf/psa/externs/ebpfPsaHashAlgorithm.cpp
> +cstring CRCChecksumAlgorithm::reflect(cstring str) {
I removed this method and commented why `polynomial` has a such value.

2022-04-06 13:25 UTC, kmateuszssak commented on backends/ebpf/psa/externs/ebpfPsaHashAlgorithm.cpp
> +        auto argList = expr->arguments->at(dataPos)->expression->to<IR::StructExpression>();
If expression is not a StructExpression then then this expression is added to the arguments vector. So there is no any error.

2022-04-06 13:34 UTC, kmateuszssak commented on backends/ebpf/tests/p4testdata/checksum-updates-crc16.p4
> +/*
I think we shouldn't. What would be the value of adding PTF testfiles to `testdata/p4_16_samples` ?

2022-04-06 13:42 UTC, kmateuszssak commented
@mbudiu-vmw I think I've addressed all of the comments.

2022-04-06 13:52 UTC, osinstom commented on backends/ebpf/psa/externs/ebpfPsaHashAlgorithm.cpp
> +            arguments.push_back(field->expression);
@kmateuszssak we could eventually simplify that as follows:

```suggestion
    if (auto argList = expr->arguments->at(dataPos)->expression->to<IR::StructExpression>()) {
        for (auto field : argList->components)
            arguments.push_back(field->expression);
```

2022-04-06 17:49 UTC, mbudiu-vmw approved these changes

2022-04-06 17:50 UTC, mbudiu-vmw commented
Unfortunately this branch now has conflicts, which you will have to resolve before we can merge.

2022-04-06 23:15 UTC, merged