Implement DirectMeter extern for eBPF backend
p4lang/p4c pull request #3243
Opened 2022-04-22 14:02 UTC by kmateuszssak

This PR adds DirectMeter extern.

Co-authored-by: Tomasz Osiński <tomasz@opennetworking.org>
Co-authored-by: Jan Palimąka <jan.palimaka@orange.com>

2022-04-22 14:04 UTC, kmateuszssak commented
@mbudiu-vmw I will improve readability of meters PTF tests later. For now, pleas review as it is.

2022-04-23 00:11 UTC, mbudiu-vmw requested changes

2022-04-23 00:11 UTC, mbudiu-vmw commented on backends/ebpf/tests/p4testdata/meters-direct-and-counter.p4
> +typedef bit<48>  EthernetAddress;
I thought you were using some common definitions of the headers using an #include.
Forgot to check this in a few previous PRs, perhaps you want to scan the recent test additions.

2022-04-23 00:11 UTC, mbudiu-vmw commented on backends/ebpf/tests/p4testdata/meters-direct-and-indirect.p4
> +control CommonDeparserImpl(packet_out packet,
I am even wondering whether you couldn't also put all these controls into the common header file... would make the code much easier to read.

2022-04-26 14:27 UTC, kmateuszssak commented
@mbudiu-vmw please review.

2022-04-26 17:38 UTC, mbudiu-vmw approved these changes

2022-04-26 17:38 UTC, mbudiu-vmw commented on backends/ebpf/tests/ptf/meters.py
> +        meter_value = build_meter_value(pir=250000, cir=250000, pbs=2500,
much better, isn't it?

2022-04-26 17:39 UTC, merged