[P4Testgen] Change Protobuf backend test case file extension to `.txtpb`
p4lang/p4c pull request #4201
Opened 2023-10-19 16:25 UTC by qobilidop

With the same reasoning as #4066. `.proto` is usually used for the schema definition file, while `.txtpb` is the current recommendation for the [text format file](https://protobuf.dev/reference/protobuf/textformat-spec/).

2023-10-19 17:22 UTC, fruffy approved these changes

2023-10-19 20:17 UTC, fruffy requested changes
Can you please also update 
https://github.com/p4lang/p4c/blob/main/backends/p4tools/modules/testgen/benchmarks/test_coverage.py#L203
?

2023-10-19 22:56 UTC, qobilidop commented
Done.

2023-10-20 12:31 UTC, fruffy approved these changes

2023-10-20 12:31 UTC, merged