Improve diagnostics for `StructExpression`
p4lang/p4c pull request #4357
Opened 2024-01-24 15:28 UTC by kfcripps

2024-01-24 16:06 UTC, jafingerhut approved these changes
I have not reviewed the C++ changes in any detail, but I have looked at the changes in the error messages, and they look reasonable to me.

2024-01-24 19:41 UTC, fruffy commented
I am not sure why a cstring could be null here. Let me debug this.

2024-01-24 19:55 UTC, kfcripps commented
> I am not sure why a cstring could be null here. Let me debug this.

Thanks!

2024-01-24 22:18 UTC, fruffy requested changes
I found the reason for the crash. No problem with your code but there is a problem with the way cstrings are initialized. 

If you just declare them `cstring var;` the internal character will be a nullptr and the cstring will be invalid. I think this is something that should be fix, not sure why the class is written this way.

Either way, applying this patch should fix the problem:
```
diff --git a/backends/p4tools/p4tools.def b/backends/p4tools/p4tools.def
index ee2066443..aec5bb13d 100644
--- a/backends/p4tools/p4tools.def
+++ b/backends/p4tools/p4tools.def
@@ -211,7 +211,7 @@ public:
     inline cstring concolicMethodName = "";
 
     toString {
-        cstring argumentStr;
+        cstring argumentStr = "";
         cstring sep = "";
         for (const auto *arg : *arguments) {
             argumentStr += sep + arg->toString();
```

2024-01-24 22:18 UTC, fruffy commented on ir/expression.def
> +    cstring toString() const;
This should either be marked `override` or implemented in the form of 
```C++
toString {
    cstring str = "{";
    if (!components.empty()) {
        cstring exprStr = components.at(0)->expression->toString();
        str += " " + components.at(0)->toString() + " = " + exprStr;
    }
    for (unsigned i = 1; i < size(); i++) {
        cstring exprStr = components.at(i)->expression->toString();
        str += ", " + components.at(i)->toString() + " = " + exprStr;
    }
    return str + " }";
}
```
like with other nodes.

2024-01-25 14:07 UTC, fruffy approved these changes

2024-01-25 14:09 UTC, fruffy commented
@kfcripps Are you able to enable automerge for these PRs? If not, I can toggle it.

2024-01-25 15:11 UTC, kfcripps commented
@fruffy How do I do that?

2024-01-25 15:12 UTC, fruffy commented
![image](https://github.com/p4lang/p4c/assets/5960321/2971d2f5-e323-49f9-95f8-aa8424ef0b21)

The CI has this option, but I believe you need merge rights for this.

2024-01-25 15:13 UTC, kfcripps commented
Yeah, I've never contributed here before, so I don't have any rights in this repo.

2024-01-25 15:17 UTC, kfcripps commented
Would that enable auto-merging for all future PRs, or do you have to enable it individually for each?

2024-01-25 15:22 UTC, vlstill commented
It is for each PR separately. In general when you have no write access, you can ask someone to merge the PR for you once you are happy with it and it is approved. In its current state it will probably have to be updated/rebased before that can be done (you will probably see a button for that).
![image](https://github.com/p4lang/p4c/assets/4070422/a616d28e-d110-40c6-8269-7d9eeec35129)

2024-01-25 15:32 UTC, kfcripps commented
Ok, I don't see why not - please enable it for my PRs. Thanks

2024-01-25 15:32 UTC, kfcripps commented
Rebased

2024-01-25 15:37 UTC, vlstill approved these changes

2024-01-25 19:25 UTC, kfcripps commented
Looks like the build_indirect job is stuck?

2024-01-25 19:29 UTC, merged