[docs] [Accessibility]Add hyperlinks to the actual resource in README
p4lang/p4c pull request #4531
Opened 2024-03-14 03:41 UTC by AdarshRawat1

- Added directory link for examples directory in DPDK backend's Guide

2024-03-14 12:38 UTC, jafingerhut approved these changes
LGTM

2024-03-15 14:51 UTC, fruffy requested changes
Instead of making just the directory the link I would also include the term before. So `examples` and `testdata/p4tc_samples`

2024-03-15 15:11 UTC, AdarshRawat1 commented
> Instead of making just the directory the link I would also include the term before. So `examples` and `testdata/p4tc_samples`

Sure, that would be a better way of linking the resource.

2024-03-16 16:34 UTC, fruffy commented on backends/ubpf/README.md
> +The sample P4 programs are located in [`examples/` directory](./examples). We have tested them with the [P4rt-OVS](https://github.com/Orange-OpenSource/p4rt-ovs) switch -
```suggestion
The sample P4 programs are located in the [`examples/` directory](./examples). We have tested them with the [P4rt-OVS](https://github.com/Orange-OpenSource/p4rt-ovs) switch - 
```

2024-03-16 16:34 UTC, fruffy commented on backends/tc/README.md
> +The sample p4 programs are located in the ["testdata/p4tc_samples" directory](../../testdata/p4tc_samples).
```suggestion
The sample p4 programs are located in the [`testdata/p4tc_samples` directory](../../testdata/p4tc_samples).
```

2024-03-16 16:59 UTC, fruffy approved these changes

2024-03-16 21:36 UTC, merged