[Docs] Non-Breaking change of "p4c" to "P4C"
p4lang/p4c pull request #4620
Opened 2024-04-15 04:35 UTC by AdarshRawat1

# Fixes 
-  #4585

# Changes 
Refactor : Current Compiler Acronym i.e. `p4c` to `P4C`  in Documentation

> This PR only focuses on the Documentation text, Without modifying any command or directory name.

2024-04-15 16:57 UTC, fruffy requested changes

2024-04-15 16:57 UTC, fruffy commented on README.md
> +1. Go to [p4lang-P4C package page on OpenSUSE Build Service](https://build.opensuse.org/package/show/home:p4lang/p4lang-p4c), click on
```suggestion
1. Go to [p4lang-p4c package page on OpenSUSE Build Service](https://build.opensuse.org/package/show/home:p4lang/p4lang-p4c), click on
```

2024-04-15 16:57 UTC, fruffy commented on README.md
> +    The compiler driver `P4C` and binaries for each of the backends are
```suggestion
    The compiler driver `p4c` and binaries for each of the backends are
```

2024-04-15 16:57 UTC, fruffy commented on README.md
> +`P4C` itself, you may run into trouble with some extensions and other p4lang
```suggestion
P4C itself, you may run into trouble with some extensions and other p4lang
```

2024-04-15 16:57 UTC, fruffy commented on README.md
> +`P4C` also depends on Google Abseil library. This library is also a pre-requisite for Protobuf of any version newer than 3.21. Therefore the use of Protobuf of suitable version automatically fulfils
```suggestion
P4C also depends on Google Abseil library. This library is also a pre-requisite for Protobuf of any version newer than 3.21. Therefore the use of Protobuf of suitable version automatically fulfils Abseil dependency. P4C typically installs its own version of Abseil using CMake's `FetchContent` module (Abseil LTS 20240116.1 at the moment).
```

2024-04-15 16:57 UTC, fruffy commented on docs/README.md
> +**P4C** is a compiler driver. The goal is to provide a consistent user interface
```suggestion
**p4c** is a compiler driver. The goal is to provide a consistent user interface
```

2024-04-15 16:57 UTC, fruffy commented on docs/README.md
> +There is an global variable `config` in P4C compiler driver that stores the build steps
```suggestion
There is an global variable `config` in the `p4c` compiler driver that stores the build steps
```

2024-04-15 16:57 UTC, fruffy commented on docs/README.md
> +User can install `P4C` to other system path by running `make install`
```suggestion
For testing purposes, `p4c` will be installed in the build/ directory when executing `make`.
Users can install `p4c` to other system path by running `make install`
```

2024-04-16 15:08 UTC, fruffy approved these changes

2024-04-17 01:13 UTC, fruffy commented
Is this ready to be merged?

2024-04-17 17:39 UTC, AdarshRawat1 commented
According to me it is ready, rest of the sitings are directory name and links.

2024-04-17 17:40 UTC, AdarshRawat1 commented
Are we planning to change the repository name in near future?

2024-04-17 17:46 UTC, fruffy commented
> According to me it is ready, rest of the sitings are directory name and links.

I was asking because you left 


    Work in progress 🚧🚀

in the description. 

>Are we planning to capitalise the repository name in near future?

No, that will stay lower case.

2024-04-17 17:59 UTC, AdarshRawat1 commented
> I was asking because you left
> 
> ```
> Work in progress 🚧🚀
> ``` 
> in the description.

I had doubts if the repository name will change or not. Since it won't change, this PR is ready to go.

2024-04-17 19:00 UTC, merged