Update ebpf comment format
p4lang/p4c pull request #4624
Opened 2024-04-17 17:51 UTC by sumit7754

I have made the following changes in ebpf(backend):

Used triple slashes (///) for commenting functions and classes.
Used double slashes (//) for comments within the code.

2024-04-17 17:58 UTC, fruffy commented
Thanks for doing this! It makes the entire compiler more consistent in style. 
Your PR is out-of-sync. You may have to rebase or merge.

2024-04-17 18:29 UTC, sumit7754 commented
You're welcome @fruffy  I'm glad to hear that it's making the compiler more consistent in style. If you have any more feedback then please let me know

2024-04-18 14:19 UTC, fruffy requested changes

2024-04-18 14:19 UTC, fruffy commented on backends/ebpf/target.h
> +/// Target XDP
```suggestion
/// Target XDP.
```

2024-04-18 16:04 UTC, fruffy approved these changes
There are still a bunch of lowercase instances and dots missing but I do not want to be too pedantic.

2024-04-18 17:50 UTC, merged