Make different Markdown files have different titles in Doxygen output
p4lang/p4c pull request #4745
Opened 2024-06-23 17:23 UTC by jafingerhut

2024-06-23 17:24 UTC, jafingerhut commented
@fruffy @AdarshRawat1 The current Doxygen-generated page here has about 4 or 5 "README" headings, and a few others that are similarly non-obvious what they are intended to be. These changes should make them all have more descriptive top level headings.

There is no difference between this PR and the other one I closed recently, except this one has the correct DCO text included in the commit.

2024-06-23 17:52 UTC, AdarshRawat1 commented
@jafingerhut Thank you for tagging the pages, this will improve Documentation .

2024-06-23 18:28 UTC, fruffy approved these changes

2024-06-23 18:30 UTC, fruffy requested changes

2024-06-23 18:30 UTC, fruffy commented on backends/p4tools/modules/testgen/lib/README.md
> +# P4testgen Library
```suggestion
# P4Testgen Library
```

2024-06-23 18:33 UTC, jafingerhut commented on backends/p4tools/modules/testgen/lib/README.md
> +# P4testgen Library
done

2024-06-24 02:30 UTC, fruffy approved these changes

2024-06-24 04:31 UTC, merged