P4Fmt reference checker
p4lang/p4c pull request #4778
Opened 2024-07-03 16:08 UTC by snapdgn

reference checker for `p4fmt` formatter

2024-07-03 20:11 UTC, qobilidop commented
Not an immediate requirement, but I think it would be great to integrate this checker with GitHub CIs eventually. For now, adding a section in the README describing its usage might be good enough.

2024-07-05 16:14 UTC, fruffy requested changes

2024-07-05 16:14 UTC, fruffy commented on backends/p4fmt/p4fmt.h
> +std::stringstream getFormattedOutput(std::filesystem::path inputFile);
Please add a triple slash comment describing this function here.

2024-07-05 16:14 UTC, fruffy commented on backends/p4fmt/p4fmt.cpp
> +        std::cerr << "Error: Failed to parse P4 file." << std::endl;
Use `::error("..")` here

2024-07-09 13:58 UTC, fruffy commented on backends/p4fmt/p4fmt.cpp
> +/// Formats a P4 program from the input file, returns formatted output
This should be in the header file.

2024-07-09 16:32 UTC, fruffy approved these changes

2024-07-09 17:45 UTC, merged